# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendations.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recommendations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\"^\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1f\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\r.GameCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"/\n\x12GameRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"F\n\x16RecommendationResponse\x12,\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x13.GameRecommendation*\xd2\x01\n\x0cGameCategory\x12\x0b\n\x07\x43LASSIC\x10\x00\x12\x0e\n\nCARD_GAMES\x10\x01\x12\x0b\n\x07\x44UELING\x10\x02\x12\x0f\n\x0b\x43OOPERATIVE\x10\x03\x12\r\n\tSTRATEGIC\x10\x04\x12\x0c\n\x08\x45\x43ONOMIC\x10\x05\x12\x14\n\x10ROLE_PLAYING_NRI\x10\x06\x12\x07\n\x03\x43\x43G\x10\x07\x12\r\n\tADVENTURE\x10\x08\x12\r\n\tDETECTIVE\x10\t\x12\r\n\tFOR_PARTY\x10\n\x12\x10\n\x0c\x46OR_CHILDREN\x10\x0b\x12\x0c\n\x08HARDCORE\x10\x0c\x32O\n\x0fRecommendations\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMECATEGORY']._serialized_start=243
  _globals['_GAMECATEGORY']._serialized_end=453
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=25
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=119
  _globals['_GAMERECOMMENDATION']._serialized_start=121
  _globals['_GAMERECOMMENDATION']._serialized_end=168
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=170
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=240
  _globals['_RECOMMENDATIONS']._serialized_start=455
  _globals['_RECOMMENDATIONS']._serialized_end=534
# @@protoc_insertion_point(module_scope)
